### PR TITLE
Fix crossects dimensions

### LINKED ISSUE #195: Need to fix MATLAB cross-sections to properly use dimensions
When MATLAB cross-sects have hard-coded coordinates (i.e. the origin), they are using floats instead of a dimensions class. This should be resolved by having the hard-coded coordinates take on the data-type of one of the dimensions variables.

For example, this is the current implementation and it is incorrect
https://github.com/Severson-Group/eMach/blob/4f746ae99e915300cebe542786a76b7eef7387cc/model_obj/crosssects/hollowCylinder/CrossSectHollowCylinder.m#L22-L25

Instead, one should use 
```matlab
x_out = feval(class(t), 0);
x_in = feval(class(t), 0);
```

All cross-sections need to be checked and updated:
- [x] `arc` @ngadiyar93 
- [x] `breadloaf` @ngadiyar93 
- [x] `hollowCylinder` @ngadiyar93 
- [x] `hollowRectangle` @ngadiyar93 
- [ ] `innerNotchedRectangle`
- [ ] `inner_rotor_stator`
- [ ] `linearMotorStator`
- [ ] `notchedRectangle`
- [ ] `outerRotor`
- [ ] `outerRotorStator`
- [ ] `parallelogram`
- [ ] `solidRectangle`
- [ ] `trapezoid`

### PR DESCRIPTION
**Pull request by ngadiyar93**
This PR fixes the following cross-sects to properly use dimensions: 

- `breadloaf`, 

- `hollowCylinder`

- `hollowRectangle`

### CODE REVIEW

File: model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m [hunk 1]
```diff
@@ -21,13 +21,13 @@
...
             validateattributes(drawer, {'DrawerBase'}, {'nonempty'});
-            axis = DimMillimeter([0,0]);
             w=obj.dim_w;
             h=obj.dim_h;
             t1=obj.dim_t1;
             t2=obj.dim_t2;
             t3=obj.dim_t3;
-            t4=obj.dim_t4;            
+            t4=obj.dim_t4;
+            axis = DimMillimeter([feval(class(w), 0),feval(class(w), 0)]);
```
Comment (Bharat-Ramadas) [inline model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: Should we be using `DimMillimeter` explicitly here instead of just `feval` ?

Comment (ngadiyar93) [reply model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: @Bharat-Ramadas I think `feval` makes more sense than `DimMillimeter`.....For example, the user may not always be specifying the dimension as `DimMillimeter` and may choose `DimInch` / `DimMeter` / any other ?

Comment (Bharat-Ramadas) [reply model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: Sorry for the lack of clarity, what I meant is why can't `axis = DimMillimeter([feval(class(w), 0),feval(class(w), 0)])` be just `axis = [feval(class(w), 0),feval(class(w), 0)]`

Comment (ngadiyar93) [reply model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: @Bharat-Ramadas Gotcha! I have fixed this...

Comment (elsevers) [reply model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: Better yet, do this: `axis = feval(class(w), [0 0])`

Comment (ngadiyar93) [reply model_obj/crosssects/hollowRectangle/CrossSectHollowRect.m]: Thanks,  just made the update.

**Review by elsevers — APPROVED** [review]

**Review by aimthiazz — APPROVED** [review]
